{{- if .Values.ui.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth2-secret
type: Opaque
stringData:
  client-id: {{ .Values.ui.auth.clientId | quote }}
  client-secret: {{ .Values.ui.auth.clientSecret | quote }}
  cookie-secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
